syblog:
  config:
    token-keep-time: 864000
    key: 114514
    bytes:
      - 5
      - 1
      - 4
    num-one-page: 8
    app-name: SYBlog
    theme-dir: file:${user.home}/SYBlog/theme

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/SYBlog/db;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE
    username: root
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  messages:
    basename: i18n.sy

  web:
    resources:
      static-locations: file:${user.home}/SYBlog/static/,classpath:static/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
server:
  port: 8080
#  http-port: 8081