spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/db;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRU
    username: root
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always